modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "banksystem"
version = "${version}"
displayName = "Bank System"
authors = "Alex Krieg"
description = '''
Adds a banking system to the game that allows players to store and withdraw money or items.
'''
#logoFile = ""

[[dependencies.banksystem]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
