modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "banksystem"
version = "${version}"
displayName = "Bank System"
authors = "Alex Krieg"
description = '''
Adds a banking system to the game that allows players to store and withdraw money or items.
'''
#logoFile = ""

[[dependencies.banksystem]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.86,)"
ordering = "AFTER"
side = "BOTH"
