modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "banksystem"
version = "${version}"
displayName = "Bank System"
authors = "Alex Krieg"
description = '''
Adds a banking system to the game that allows players to store and withdraw money or items.
'''
#logoFile = ""

[[dependencies.banksystem]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.banksystem]]
modId = "architectury"
type = "required"
versionRange = "[12.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "banksystem.mixins.json"
